# Generated by Django 3.1.2 on 2021-03-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.IntegerField()),
                ('stu_name', models.CharField(max_length=50)),
                ('stu_city', models.CharField(max_length=150)),
                ('stu_contactno', models.IntegerField()),
                ('stu_email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'tbl_student',
            },
        ),
    ]
